version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: .
    depends_on:
      - db
    platform: linux/amd64 # Patch for M1 Mac
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  postgres_data:
